apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steelengine-home-pvc
  labels:
    app: steelengine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
