export const browserCoreExamples = [
  "recall browser status",
  "recall browser start",
  "recall browser stop",
  "recall browser tabs",
  "recall browser open https://example.com",
  "recall browser focus abcd1234",
  "recall browser close abcd1234",
  "recall browser screenshot",
  "recall browser screenshot --full-page",
  "recall browser screenshot --ref 12",
  "recall browser snapshot",
  "recall browser snapshot --format aria --limit 200",
  "recall browser snapshot --efficient",
  "recall browser snapshot --labels",
];

export const browserActionExamples = [
  "recall browser navigate https://example.com",
  "recall browser resize 1280 720",
  "recall browser click 12 --double",
  'recall browser type 23 "hello" --submit',
  "recall browser press Enter",
  "recall browser hover 44",
  "recall browser drag 10 11",
  "recall browser select 9 OptionA OptionB",
  "recall browser upload /tmp/recall/uploads/file.pdf",
  'recall browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "recall browser dialog --accept",
  'recall browser wait --text "Done"',
  "recall browser evaluate --fn '(el) => el.textContent' --ref 7",
  "recall browser console --level error",
  "recall browser pdf",
];
