import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-steelengine writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.steelengine.mac"
let gatewayLaunchdLabel = "ai.steelengine.gateway"
let nodeLaunchdLabel = "ai.steelengine.node"
let onboardingVersionKey = "steelengine.onboardingVersion"
let onboardingSeenKey = "steelengine.onboardingSeen"
let onboardingSystemAgentPendingKey = "steelengine.onboardingSystemAgentPending"
// Pre-rename releases persisted pending activations under the Crestodian key.
let onboardingSystemAgentPendingRetiredKey = "steelengine.onboardingCrestodianPending"
let currentOnboardingVersion = 8
let pauseDefaultsKey = "steelengine.pauseEnabled"
let iconAnimationsEnabledKey = "steelengine.iconAnimationsEnabled"
let swabbleEnabledKey = "steelengine.swabbleEnabled"
let swabbleTriggersKey = "steelengine.swabbleTriggers"
let voiceWakeTriggerChimeKey = "steelengine.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "steelengine.voiceWakeSendChime"
let showDockIconKey = "steelengine.showDockIcon"
let defaultVoiceWakeTriggers = ["steelengine"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "steelengine.voiceWakeMicID"
let voiceWakeMicNameKey = "steelengine.voiceWakeMicName"
let voiceWakeLocaleKey = "steelengine.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "steelengine.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "steelengine.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "steelengine.voiceWakeTriggersTalkMode"
let talkEnabledKey = "steelengine.talkEnabled"
let talkPhaseSoundsEnabledKey = "steelengine.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "steelengine.talkShiftToStopEnabled"
let iconOverrideKey = "steelengine.iconOverride"
let connectionModeKey = "steelengine.connectionMode"
let remoteTargetKey = "steelengine.remoteTarget"
let remoteIdentityKey = "steelengine.remoteIdentity"
let remoteProjectRootKey = "steelengine.remoteProjectRoot"
let remoteCliPathKey = "steelengine.remoteCliPath"
let canvasEnabledKey = "steelengine.canvasEnabled"
let quickChatEnabledKey = "steelengine.quickChatEnabled"
let cameraEnabledKey = "steelengine.cameraEnabled"
let computerControlEnabledKey = "steelengine.computerControlEnabled"
let locationModeKey = "steelengine.locationMode"
let locationPreciseKey = "steelengine.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "steelengine.peekabooBridgeEnabled"
let deepLinkKeyKey = "steelengine.deepLinkKey"
let cliInstallPromptedVersionKey = "steelengine.cliInstallPromptedVersion"
let cliInstallPolicyKey = "steelengine.cliInstallPolicy"
let cliManagedRestartPendingKey = "steelengine.cliManagedRestartPending"
let postAppUpdateReceiptKey = "steelengine.postAppUpdateReceipt"
let lastLaunchedAppVersionKey = "steelengine.lastLaunchedAppVersion"
let cliValidatedExecutableKey = "steelengine.cliValidatedExecutable"
let cliValidatedVersionKey = "steelengine.cliValidatedVersion"
let macNodeIdentityProfileKey = "steelengine.macNodeIdentityProfile"
let heartbeatsEnabledKey = "steelengine.heartbeatsEnabled"
let debugPaneEnabledKey = "steelengine.debugPaneEnabled"
let debugFileLogEnabledKey = "steelengine.debug.fileLogEnabled"
let appLogLevelKey = "steelengine.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
