#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/docker-build.sh"
IMAGE_NAME="${RECALL_INSTALL_E2E_IMAGE:-recall-install-e2e:local}"
INSTALL_URL="${RECALL_INSTALL_URL:-https://recall.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
RECALL_E2E_MODELS="${RECALL_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker_build_run install-e2e-build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e RECALL_INSTALL_URL="$INSTALL_URL" \
  -e RECALL_INSTALL_TAG="${RECALL_INSTALL_TAG:-latest}" \
  -e RECALL_E2E_MODELS="$RECALL_E2E_MODELS" \
  -e RECALL_INSTALL_E2E_OPENAI_MODEL="${RECALL_INSTALL_E2E_OPENAI_MODEL:-}" \
  -e RECALL_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS="${RECALL_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS:-}" \
  -e RECALL_INSTALL_E2E_PREVIOUS="${RECALL_INSTALL_E2E_PREVIOUS:-}" \
  -e RECALL_INSTALL_E2E_SKIP_PREVIOUS="${RECALL_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e RECALL_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${RECALL_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-300}" \
  -e RECALL_INSTALL_E2E_AGENT_TURNS_PARALLEL="${RECALL_INSTALL_E2E_AGENT_TURNS_PARALLEL:-1}" \
  -e RECALL_INSTALL_E2E_AGENT_TOOL_SMOKE="${RECALL_INSTALL_E2E_AGENT_TOOL_SMOKE:-1}" \
  -e RECALL_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
